name: proxy

on:
  schedule:
    - cron: '0 */2 * * *'  # Her 2 saatte bir çalıştır
  workflow_dispatch:  # Manuel çalıştırmaya izin ver

jobs:
 extract-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Depoyu klonla
        uses: actions/checkout@v4
      
      - name: Python'u kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml playwright bs4 rapidfuzz fuzzywuzzy python-Levenshtein python-dateutil python-dotenv selenium webdriver-manager pillow
          playwright install 

      - name: Betiği çalıştır
        run: |
          if [ -f .env ]; then
            export $(grep -v '^#' .env | xargs)
          else
            echo ".env dosyası bulunamadı. Depoda mevcut olduğundan emin olun."
            exit 1
          fi
          
          if [ -z "${LISTA}" ]; then
            echo "LISTA değişkeni tanımlı değil. .env dosyanızı kontrol edin."
            exit 1
          fi
          
          python "${LISTA}.py"
      
      - name: Git yapılandırmasını ayarla
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Yerel değişiklikleri sakla (varsa)
        run: |
          git diff --quiet || git stash

      - name: Uzaktaki depodan son değişiklikleri indir
        run: git pull --rebase origin main

      - name: Saklanan değişiklikleri geri yükle (varsa)
        run: |
          git stash list | grep -q "stash@{0}" && git stash pop || echo "Geri yüklenecek değişiklik yok"

      - name: Oluşturulan dosyayı commite ekle
        run: |
          git add .
          git commit -m "GÜNCELLEME" || echo "Commitlenecek değişiklik yok"

      - name: Değişiklikleri gönder (push)
        run: git push
